on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        log-level: verbose
        server: ssh.strato.de
        username: sftp_meeting@meeting.fail
        password: ${{ secrets.TEST }}
        protocol: ftps
        port: 22
